spring:
  application:
    name: dubbo-message-service
  profiles:
    active: dev

mybatis-plus:
  configuration:
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  scan:
    base-packages: com.example.service
  protocol:
    name: dubbo
    port: 8888
