spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.163.184:30006/dubbo-app?useSSL=false&charset=utf8mb4
  redis:
    host: 192.168.163.184
    port: 30001
dubbo:
  registry:
    address: N/A
  # address: nacos://192.168.163.184:8848/?username=nacos&password=nacos
