spring:
  redis:
    host: 192.168.163.184
    port: 30001



netty:
  address: 127.0.0.1
  port: 8088


dubbo:
  registry:
    address: nacos://192.168.163.184:8848/?username=nacos&password=nacos
  protocol:
    name: dubbo