spring:
  application:
    name: dubbo-web
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false

  profiles:
    active: dev

