dubbo:
  registry:
    # address: zookeeper://127.0.0.1:2181
    # address: nacos://dev.k8s:80/?username=nacos&password=nacos
    address: nacos://nacosregistry:8848/?username=nacos&password=nacos
  protocol:
    name: dubbo
server:
  port: 80

