spring:
  application:
    name: dubbo-web
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false

dubbo:
  registry:
    # address: zookeeper://127.0.0.1:2181
    # address: nacos://dev.k8s:80/?username=nacos&password=nacos
    address: nacos://192.168.163.184:8848/?username=nacos&password=nacos
  protocol:
    name: dubbo
server:
  port: 8081

